import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class StudentCreate {
  @ApiProperty()
  name: string;
  @ApiProperty()
  email: string;
}

export class Student {
  @ApiProperty()
  id: number;
  @ApiProperty()
  name: string;
  @ApiProperty()
  email: string;
}
