import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class AssignmentCreate {
  @ApiProperty()
  title: string;
  @ApiProperty()
  description: string;
  @ApiProperty()
  deadline: Date;
}

export class Assignment {
  @ApiProperty()
  id: number;
  @ApiProperty()
  title: string;
  @ApiProperty()
  description: string;
  @ApiProperty()
  deadline: Date;
}
