import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class DealCreate {
  @ApiProperty()
  name: string;
  @ApiProperty()
  amount: string;
  @ApiProperty()
  status: string;
}

export class Deal {
  @ApiProperty()
  id: number;
  @ApiProperty()
  name: string;
  @ApiProperty()
  amount: string;
  @ApiProperty()
  status: string;
}
